[package]
name = "extractor"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.140"
tokio = { version = "1.46.1", features = ["full"] }
tunecore = { version = "0.1.0", path = "tunecore" }
