[package]
name = "extractor"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
futures-util = "0.3.31"
mongodb = "3.2.4"
serde_json = "1.0.140"
thiserror = "2.0.12"
tokio = { version = "1.46.1", features = ["full"] }
tunecore = { version = "0.1.0", path = "tunecore" }
